# Generated by Django 6.0.5 on 2026-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('budget', models.IntegerField(default=0)),
                ('source', models.CharField(default='Website', max_length=100)),
                ('status', models.CharField(default='open', max_length=50)),
                ('assignedTo', models.CharField(blank=True, max_length=100, null=True)),
                ('assignedToName', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('createdAt', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedAt', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
