# Generated by Django 6.0.5 on 2026-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_usedrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
